spring:
  application:
    name: taxprep
  web:
    resources:
        static-locations: 
          - classpath:/react/dist

#   datasource:
#       url: ${DB_URL}
#       username: ${DB_USERNAME}
#       password: ${DB_PASSWORD}                              

  jpa:
      database-platform: org.hibernate.dialect.H2Dialect      
      defer-datasource-initialization: true                   
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      exclude: frontend/**

server:
  port: ${PROGRAM_PORT} 

  